1

   Abaqus 2022                                  Date 04-apr-2025   Time 09:56:41
   For use by NORGES TEKNISK NATURVITENSKAPELIGE UNIVERSITET under license from Dassault Systemes or its subsidiary.

                                                                                 
                                                                                 
 STEP    1     INCREMENT     1     STEP TIME    0.00    


                        S T E P       1     C A L C U L A T I O N   O F   E I G E N V A L U E S

                                            F O R   B U C K L I N G   P R E D I C T I O N



                                                                                          

     THE SUBSPACE ITERATION METHOD IS USED FOR THIS ANALYSIS
     NUMBER OF EIGENVALUES                      2
     MAXIMUM NUMBER OF ITERATIONS                    500
     NUMBER OF VECTORS IN ITERATION                    4
     THE BUCKLING MODE CONSTRAINTS 
      ARE DEFINED AS LOAD CASE 2
                              ONLY INITIAL STRESS EFFECTS ARE INCLUDED IN THE
                              STIFFNESS MATRIX

     THIS IS A LINEAR PERTURBATION STEP.
     ALL LOADS ARE DEFINED AS CHANGE IN LOAD TO THE REFERENCE STATE

     EXTRAPOLATION WILL NOT BE USED

     CHARACTERISTIC ELEMENT LENGTH      19.0    

     DETAILS REGARDING ACTUAL SOLUTION WAVEFRONT REQUESTED

     DETAILED OUTPUT OF DIAGNOSTICS TO DATABASE REQUESTED

     PRINT OF INCREMENT NUMBER, TIME, ETC., TO THE MESSAGE FILE EVERY     1  INCREMENTS
 
	SYMMETRIC DIRECT SPARSE SOLVER RUNNING ON
 	1 HOST:        1 MPI RANK  x 1 THREAD
 	NUMBER OF EQUATIONS:     23508
 	NUMBER OF RHS:           1
 	NUMBER OF FLOPS:         1.547e+09

     CHECK POINT   START OF SOLVER    

     CHECK POINT  END OF SOLVER       

       ELAPSED USER TIME (SEC)      =  0.20000    
       ELAPSED SYSTEM TIME (SEC)    =  0.10000    
       ELAPSED TOTAL CPU TIME (SEC) =  0.30000    
       ELAPSED WALLCLOCK TIME (SEC) =          0
 
     ITERATION 1
      1       -1.733951e+01    
      2       3.252691e+01     
      3       -5.049594e+01    
      4       1.909558e+03     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 2
      1       -7.538158e+00    
      2       1.304183e+01     
      3       -1.515213e+01    
      4       4.613982e+02     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 3
      1       -5.555040e+00    
      2       -9.285918e+00    
      3       1.075026e+01     
      4       -2.576795e+02    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 4
      1       -4.614120e+00    
      2       -6.590680e+00    
      3       9.631357e+00     
      4       -1.038005e+02    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 5
      1       -4.022739e+00    
      2       -5.301831e+00    
      3       8.803822e+00     
      4       -7.012546e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 6
      1       -3.502829e+00    
      2       -4.783351e+00    
      3       8.088946e+00     
      4       -6.002981e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 7
      1       -3.069039e+00    
      2       -4.619205e+00    
      3       7.411649e+00     
      4       -5.973590e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 8
      1       -2.743406e+00    
      2       -4.596846e+00    
      3       6.758259e+00     
      4       -6.582773e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 9
      1       -2.504298e+00    
      2       -4.641327e+00    
      3       6.143858e+00     
      4       -7.764028e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 10
      1       -2.327635e+00    
      2       -4.724890e+00    
      3       5.585991e+00     
      4       -9.515986e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 11
      1       -2.195627e+00    
      2       -4.835563e+00    
      3       5.093755e+00     
      4       -1.174546e+02    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 12
      1       -2.095997e+00    
      2       4.667385e+00     
      3       -4.966772e+00    
      4       -1.407729e+02    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 13
      1       -2.020290e+00    
      2       4.301556e+00     
      3       -5.113217e+00    
      4       -1.580849e+02    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 14
      1       -1.962596e+00    
      2       3.988599e+00     
      3       -5.268866e+00    
      4       -1.633626e+02    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 15
      1       -1.918704e+00    
      2       3.720540e+00     
      3       -5.425700e+00    
      4       -1.573819e+02    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 16
      1       -1.885553e+00    
      2       3.490085e+00     
      3       -5.572811e+00    
      4       -1.466055e+02    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 17
      1       -1.860874e+00    
      2       3.290975e+00     
      3       -5.695988e+00    
      4       -1.377526e+02    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 18
      1       -1.842958e+00    
      2       3.118009e+00     
      3       -5.778304e+00    
      4       -1.359515e+02    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 19
      1       -1.830498e+00    
      2       2.966939e+00     
      3       -5.802419e+00    
      4       -1.476863e+02    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 20
      1       -1.822481e+00    
      2       2.834320e+00     
      3       -5.754715e+00    
      4       -1.927674e+02    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 21
      1       -1.818115e+00    
      2       2.717361e+00     
      3       -5.629957e+00    
      4       -4.233658e+02    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 22
      1       -1.816776e+00    
      2       2.613798e+00     
      3       -5.433843e+00    
      4       5.463499e+02     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 23
      1       -1.817969e+00    
      2       2.521786e+00     
      3       -5.181576e+00    
      4       1.353826e+02     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 24
      1       -1.821299e+00    
      2       2.439805e+00     
      3       -4.893283e+00    
      4       7.042022e+01     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 25
      1       -1.826450e+00    
      2       2.366594e+00     
      3       -4.588993e+00    
      4       4.524081e+01     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 26
      1       -1.833171e+00    
      2       2.301092e+00     
      3       -4.285307e+00    
      4       3.235964e+01     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 27
      1       -1.841258e+00    
      2       2.242390e+00     
      3       -3.994186e+00    
      4       2.475212e+01     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 28
      1       -1.850553e+00    
      2       2.189698e+00     
      3       -3.723202e+00    
      4       1.983674e+01     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 29
      1       -1.860928e+00    
      2       2.142317e+00     
      3       -3.476408e+00    
      4       1.645714e+01     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 30
      1       -1.872282e+00    
      2       2.099622e+00     
      3       -3.255329e+00    
      4       1.402489e+01     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 31
      1       -1.884539e+00    
      2       2.061044e+00     
      3       -3.059798e+00    
      4       1.221224e+01     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 32
      1       -1.897639e+00    
      2       2.026070e+00     
      3       -2.888593e+00    
      4       1.082377e+01     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 33
      1       -1.911540e+00    
      2       1.994233e+00     
      3       -2.739889e+00    
      4       9.736468e+00     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 34
      1       -1.926209e+00    
      2       1.965113e+00     
      3       -2.611564e+00    
      4       8.869485e+00     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 35
      1       1.938337e+00     
      2       -1.941626e+00    
      3       -2.501408e+00    
      4       8.167660e+00     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 36
      1       1.913582e+00     
      2       -1.957773e+00    
      3       -2.407247e+00    
      4       7.592196e+00     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 37
      1       1.890567e+00     
      2       -1.974636e+00    
      3       -2.327032e+00    
      4       7.115069e+00     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 38
      1       1.869060e+00     
      2       -1.992192e+00    
      3       -2.258891e+00    
      4       6.715573e+00     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 39
      1       1.848867e+00     
      2       -2.010381e+00    
      3       -2.201177e+00    
      4       6.378111e+00     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 40
      1       1.829831e+00     
      2       -2.029011e+00    
      3       -2.152570e+00    
      4       6.090731e+00     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 41
      1       1.811827e+00     
      2       -2.047193e+00    
      3       -2.112641e+00    
      4       5.844147e+00     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 42
      1       1.794759e+00     
      2       -2.056814e+00    
      3       -2.088360e+00    
      4       5.631051e+00     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 43
      1       1.778547e+00     
      2       -2.038018e+00    
      3       -2.098609e+00    
      4       5.445633e+00     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 44
      1       1.763132e+00     
      2       -2.013961e+00    
      3       -2.119404e+00    
      4       5.283230e+00     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 45
      1       1.748465e+00     
      2       -1.992281e+00    
      3       -2.142412e+00    
      4       5.140071e+00     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 46
      1       1.734509e+00     
      2       -1.973282e+00    
      3       -2.166748e+00    
      4       5.013086e+00     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 47
      1       1.721230e+00     
      2       -1.956657e+00    
      3       -2.192238e+00    
      4       4.899758e+00     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 48
      1       1.708600e+00     
      2       -1.942046e+00    
      3       -2.218847e+00    
      4       4.798014e+00     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 49
      1       1.696595e+00     
      2       -1.929119e+00    
      3       -2.246585e+00    
      4       4.706138e+00     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 50
      1       1.685190e+00     
      2       -1.917591e+00    
      3       -2.275477e+00    
      4       4.622702e+00     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 51
      1       1.674364e+00     
      2       -1.907221e+00    
      3       -2.305559e+00    
      4       4.546514e+00     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 52
      1       1.664094e+00     
      2       -1.897806e+00    
      3       -2.336874e+00    
      4       4.476574e+00     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 53
      1       1.654359e+00     
      2       -1.889180e+00    
      3       -2.369469e+00    
      4       4.412040e+00     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 54
      1       1.645138e+00     
      2       -1.881201e+00    
      3       -2.403394e+00    
      4       4.352200e+00     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 55
      1       1.636409e+00     
      2       -1.873754e+00    
      3       -2.438705e+00    
      4       4.296450e+00     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 56
      1       1.628150e+00     
      2       -1.866745e+00    
      3       -2.475461e+00    
      4       4.244277e+00     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 57
      1       1.620341e+00     
      2       -1.860095e+00    
      3       -2.513725e+00    
      4       4.195242e+00     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 58
      1       1.612961e+00     
      2       -1.853737e+00    
      3       -2.553563e+00    
      4       4.148967e+00     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 59
      1       1.605989e+00     
      2       -1.847621e+00    
      3       -2.595047e+00    
      4       4.105130e+00     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 60
      1       1.599404e+00     
      2       -1.841700e+00    
      3       -2.638254e+00    
      4       4.063449e+00     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 61
      1       1.593187e+00     
      2       -1.835941e+00    
      3       -2.683265e+00    
      4       4.023682e+00     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 62
      1       1.587319e+00     
      2       -1.830313e+00    
      3       -2.730166e+00    
      4       3.985619e+00     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 63
      1       1.581780e+00     
      2       -1.824793e+00    
      3       -2.779048e+00    
      4       3.949075e+00     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 64
      1       1.576553e+00     
      2       -1.819361e+00    
      3       -2.830010e+00    
      4       3.913889e+00     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 65
      1       1.571620e+00     
      2       -1.814002e+00    
      3       -2.883155e+00    
      4       3.879919e+00     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 66
      1       1.566963e+00     
      2       -1.808702e+00    
      3       -2.938593e+00    
      4       3.847040e+00     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 67
      1       1.562566e+00     
      2       -1.803452e+00    
      3       -2.996444e+00    
      4       3.815140e+00     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 68
      1       1.558415e+00     
      2       -1.798244e+00    
      3       -3.056831e+00    
      4       3.784123e+00     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 69
      1       1.554493e+00     
      2       -1.793071e+00    
      3       -3.119888e+00    
      4       3.753899e+00     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 70
      1       1.550786e+00     
      2       -1.787929e+00    
      3       -3.185759e+00    
      4       3.724391e+00     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 71
      1       1.547280e+00     
      2       -1.782813e+00    
      3       -3.254593e+00    
      4       3.695528e+00     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 72
      1       1.543963e+00     
      2       -1.777722e+00    
      3       -3.326554e+00    
      4       3.667247e+00     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 73
      1       1.540822e+00     
      2       -1.772652e+00    
      3       -3.401814e+00    
      4       3.639491e+00     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 74
      1       1.537846e+00     
      2       -1.767602e+00    
      3       -3.480557e+00    
      4       3.612209e+00     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 75
      1       1.535022e+00     
      2       -1.762572e+00    
      3       -3.562980e+00    
      4       3.585354e+00     
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 76
      1       1.532341e+00     
      2       -1.757562e+00    
      3       3.558884e+00     
      4       -3.649294e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 77
      1       1.529792e+00     
      2       -1.752570e+00    
      3       3.532759e+00     
      4       -3.739724e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 78
      1       1.527366e+00     
      2       -1.747599e+00    
      3       3.506946e+00     
      4       -3.834511e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 79
      1       1.525053e+00     
      2       -1.742647e+00    
      3       3.481411e+00     
      4       -3.933914e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 80
      1       1.522847e+00     
      2       -1.737716e+00    
      3       3.456127e+00     
      4       -4.038209e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 81
      1       1.520737e+00     
      2       -1.732806e+00    
      3       3.431065e+00     
      4       -4.147693e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 82
      1       1.518718e+00     
      2       -1.727919e+00    
      3       3.406203e+00     
      4       -4.262685e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 83
      1       1.516782e+00     
      2       -1.723055e+00    
      3       3.381518e+00     
      4       -4.383528e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 84
      1       1.514922e+00     
      2       -1.718216e+00    
      3       3.356989e+00     
      4       -4.510590e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 85
      1       1.513132e+00     
      2       -1.713403e+00    
      3       3.332600e+00     
      4       -4.644266e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 86
      1       1.511407e+00     
      2       -1.708616e+00    
      3       3.308334e+00     
      4       -4.784984e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 87
      1       1.509741e+00     
      2       -1.703858e+00    
      3       3.284175e+00     
      4       -4.933204e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 88
      1       1.508129e+00     
      2       -1.699129e+00    
      3       3.260112e+00     
      4       -5.089422e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 89
      1       1.506567e+00     
      2       -1.694430e+00    
      3       3.236132e+00     
      4       -5.254173e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 90
      1       1.505050e+00     
      2       -1.689762e+00    
      3       3.212227e+00     
      4       -5.428037e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 91
      1       1.503573e+00     
      2       -1.685128e+00    
      3       3.188386e+00     
      4       -5.611641e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 92
      1       1.502134e+00     
      2       -1.680527e+00    
      3       3.164603e+00     
      4       -5.805663e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 93
      1       1.500729e+00     
      2       -1.675961e+00    
      3       3.140872e+00     
      4       -6.010839e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 94
      1       1.499354e+00     
      2       -1.671431e+00    
      3       3.117189e+00     
      4       -6.227968e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 95
      1       1.498007e+00     
      2       -1.666938e+00    
      3       3.093549e+00     
      4       -6.457917e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 96
      1       1.496685e+00     
      2       -1.662483e+00    
      3       3.069951e+00     
      4       -6.701633e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 97
      1       1.495386e+00     
      2       -1.658067e+00    
      3       3.046393e+00     
      4       -6.960142e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 98
      1       1.494107e+00     
      2       -1.653691e+00    
      3       3.022876e+00     
      4       -7.234566e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 99
      1       1.492846e+00     
      2       -1.649355e+00    
      3       2.999401e+00     
      4       -7.526132e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 100
      1       1.491601e+00     
      2       -1.645061e+00    
      3       2.975969e+00     
      4       -7.836178e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 101
      1       1.490371e+00     
      2       -1.640808e+00    
      3       2.952584e+00     
      4       -8.166172e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 102
      1       1.489153e+00     
      2       -1.636599e+00    
      3       2.929249e+00     
      4       -8.517722e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 103
      1       1.487948e+00     
      2       -1.632434e+00    
      3       2.905970e+00     
      4       -8.892597e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 104
      1       1.486753e+00     
      2       -1.628312e+00    
      3       2.882751e+00     
      4       -9.292738e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 105
      1       1.485567e+00     
      2       -1.624236e+00    
      3       2.859599e+00     
      4       -9.720289e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 106
      1       1.484389e+00     
      2       -1.620205e+00    
      3       2.836521e+00     
      4       -1.017761e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 107
      1       1.483219e+00     
      2       -1.616219e+00    
      3       2.813524e+00     
      4       -1.066732e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 108
      1       1.482056e+00     
      2       -1.612280e+00    
      3       2.790616e+00     
      4       -1.119231e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 109
      1       1.480899e+00     
      2       -1.608388e+00    
      3       2.767806e+00     
      4       -1.175578e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 110
      1       1.479747e+00     
      2       -1.604542e+00    
      3       2.745102e+00     
      4       -1.236131e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 111
      1       1.478601e+00     
      2       -1.600744e+00    
      3       2.722514e+00     
      4       -1.301287e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 112
      1       1.477459e+00     
      2       -1.596994e+00    
      3       2.700051e+00     
      4       -1.371489e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 113
      1       1.476321e+00     
      2       -1.593291e+00    
      3       2.677722e+00     
      4       -1.447233e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 114
      1       1.475188e+00     
      2       -1.589637e+00    
      3       2.655538e+00     
      4       -1.529074e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 115
      1       1.474058e+00     
      2       -1.586031e+00    
      3       2.633507e+00     
      4       -1.617635e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 116
      1       1.472933e+00     
      2       -1.582473e+00    
      3       2.611639e+00     
      4       -1.713619e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 117
      1       1.471811e+00     
      2       -1.578963e+00    
      3       2.589944e+00     
      4       -1.817816e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 118
      1       1.470693e+00     
      2       -1.575502e+00    
      3       2.568431e+00     
      4       -1.931120e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 119
      1       1.469579e+00     
      2       -1.572089e+00    
      3       2.547109e+00     
      4       -2.054543e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 120
      1       1.468468e+00     
      2       -1.568725e+00    
      3       2.525986e+00     
      4       -2.189236e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 121
      1       1.467362e+00     
      2       -1.565410e+00    
      3       2.505072e+00     
      4       -2.336505e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 122
      1       1.466259e+00     
      2       -1.562142e+00    
      3       2.484375e+00     
      4       -2.497841e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 123
      1       1.465161e+00     
      2       -1.558923e+00    
      3       2.463901e+00     
      4       -2.674948e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 124
      1       1.464067e+00     
      2       -1.555752e+00    
      3       2.443659e+00     
      4       -2.869776e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 125
      1       1.462978e+00     
      2       -1.552630e+00    
      3       2.423654e+00     
      4       -3.084562e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 126
      1       1.461893e+00     
      2       -1.549554e+00    
      3       2.403894e+00     
      4       -3.321879e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 127
      1       1.460814e+00     
      2       -1.546527e+00    
      3       2.384384e+00     
      4       -3.584682e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 128
      1       1.459739e+00     
      2       -1.543546e+00    
      3       2.365129e+00     
      4       -3.876382e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 129
      1       1.458670e+00     
      2       -1.540613e+00    
      3       2.346135e+00     
      4       -4.200905e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 130
      1       1.457607e+00     
      2       -1.537726e+00    
      3       2.327404e+00     
      4       -4.562778e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 131
      1       1.456550e+00     
      2       -1.534886e+00    
      3       2.308942e+00     
      4       -4.967213e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 132
      1       1.455500e+00     
      2       -1.532093e+00    
      3       2.290751e+00     
      4       -5.420193e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 133
      1       1.454456e+00     
      2       -1.529345e+00    
      3       2.272834e+00     
      4       -5.928565e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 134
      1       1.453418e+00     
      2       -1.526642e+00    
      3       2.255192e+00     
      4       -6.500106e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 135
      1       1.452388e+00     
      2       -1.523985e+00    
      3       2.237829e+00     
      4       -7.143566e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 136
      1       1.451365e+00     
      2       -1.521372e+00    
      3       2.220744e+00     
      4       -7.868639e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 137
      1       1.450350e+00     
      2       -1.518803e+00    
      3       2.203939e+00     
      4       -8.685818e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 138
      1       1.449343e+00     
      2       -1.516279e+00    
      3       2.187414e+00     
      4       -9.606060e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 139
      1       1.448344e+00     
      2       -1.513798e+00    
      3       2.171169e+00     
      4       -1.064014e+02    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 140
      1       1.447353e+00     
      2       -1.511360e+00    
      3       2.155204e+00     
      4       -1.179754e+02    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 141
      1       1.446371e+00     
      2       -1.508965e+00    
      3       2.139517e+00     
      4       -1.308471e+02    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 142
      1       1.445398e+00     
      2       -1.506612e+00    
      3       2.124108e+00     
      4       -1.450243e+02    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 143
      1       1.444434e+00     
      2       -1.504300e+00    
      3       2.108974e+00     
      4       -1.604222e+02    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 144
      1       1.443479e+00     
      2       -1.502030e+00    
      3       2.094115e+00     
      4       -1.768172e+02    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 145
      1       1.442534e+00     
      2       -1.499801e+00    
      3       2.079528e+00     
      4       -1.937975e+02    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 146
      1       1.441598e+00     
      2       -1.497611e+00    
      3       2.065211e+00     
      4       -2.107219e+02    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 147
      1       1.440672e+00     
      2       -1.495462e+00    
      3       2.051161e+00     
      4       -2.267097e+02    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 148
      1       1.439757e+00     
      2       -1.493352e+00    
      3       2.037376e+00     
      4       -2.406889e+02    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 149
      1       1.438851e+00     
      2       -1.491281e+00    
      3       2.023852e+00     
      4       -2.515234e+02    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 150
      1       1.437956e+00     
      2       -1.489248e+00    
      3       2.010586e+00     
      4       -2.582109e+02    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 151
      1       1.437072e+00     
      2       -1.487252e+00    
      3       1.997576e+00     
      4       -2.601020e+02    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 152
      1       1.436198e+00     
      2       -1.485294e+00    
      3       1.984817e+00     
      4       -2.570595e+02    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 153
      1       1.435335e+00     
      2       -1.483373e+00    
      3       1.972307e+00     
      4       -2.494882e+02    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 154
      1       1.434483e+00     
      2       -1.481488e+00    
      3       1.960042e+00     
      4       -2.382236e+02    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 155
      1       1.433642e+00     
      2       -1.479639e+00    
      3       1.948017e+00     
      4       -2.243307e+02    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 156
      1       1.432812e+00     
      2       -1.477825e+00    
      3       1.936230e+00     
      4       -2.088945e+02    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 157
      1       1.431993e+00     
      2       -1.476045e+00    
      3       1.924676e+00     
      4       -1.928649e+02    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 158
      1       1.431185e+00     
      2       -1.474300e+00    
      3       1.913352e+00     
      4       -1.769792e+02    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 159
      1       1.430389e+00     
      2       -1.472589e+00    
      3       1.902253e+00     
      4       -1.617487e+02    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 160
      1       1.429604e+00     
      2       -1.470910e+00    
      3       1.891376e+00     
      4       -1.474872e+02    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 161
      1       1.428831e+00     
      2       -1.469265e+00    
      3       1.880717e+00     
      4       -1.343541e+02    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 162
      1       1.428069e+00     
      2       -1.467651e+00    
      3       1.870273e+00     
      4       -1.224000e+02    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 163
      1       1.427318e+00     
      2       -1.466069e+00    
      3       1.860038e+00     
      4       -1.116043e+02    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 164
      1       1.426579e+00     
      2       -1.464518e+00    
      3       1.850009e+00     
      4       -1.019039e+02    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 165
      1       1.425851e+00     
      2       -1.462998e+00    
      3       1.840183e+00     
      4       -9.321364e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 166
      1       1.425135e+00     
      2       -1.461508e+00    
      3       1.830555e+00     
      4       -8.543963e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 167
      1       1.424430e+00     
      2       -1.460048e+00    
      3       1.821122e+00     
      4       -7.848740e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 168
      1       1.423736e+00     
      2       -1.458616e+00    
      3       1.811880e+00     
      4       -7.226688e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 169
      1       1.423054e+00     
      2       -1.457214e+00    
      3       1.802825e+00     
      4       -6.669484e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 170
      1       1.422384e+00     
      2       -1.455839e+00    
      3       1.793953e+00     
      4       -6.169596e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 171
      1       1.421724e+00     
      2       -1.454492e+00    
      3       1.785262e+00     
      4       -5.720301e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 172
      1       1.421076e+00     
      2       -1.453173e+00    
      3       1.776747e+00     
      4       -5.315653e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 173
      1       1.420439e+00     
      2       -1.451880e+00    
      3       1.768404e+00     
      4       -4.950420e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 174
      1       1.419813e+00     
      2       -1.450613e+00    
      3       1.760231e+00     
      4       -4.620022e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 175
      1       1.419198e+00     
      2       -1.449372e+00    
      3       1.752223e+00     
      4       -4.320454e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 176
      1       1.418595e+00     
      2       -1.448157e+00    
      3       1.744379e+00     
      4       -4.048216e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 177
      1       1.418002e+00     
      2       -1.446966e+00    
      3       1.736693e+00     
      4       -3.800254e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 178
      1       1.417420e+00     
      2       -1.445800e+00    
      3       1.729164e+00     
      4       -3.573898e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 179
      1       1.416848e+00     
      2       -1.444657e+00    
      3       1.721787e+00     
      4       -3.366813e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 180
      1       1.416288e+00     
      2       -1.443539e+00    
      3       1.714560e+00     
      4       -3.176954e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 181
      1       1.415738e+00     
      2       -1.442443e+00    
      3       1.707480e+00     
      4       -3.002525e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 182
      1       1.415198e+00     
      2       -1.441370e+00    
      3       1.700544e+00     
      4       -2.841951e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 183
      1       1.414668e+00     
      2       -1.440320e+00    
      3       1.693748e+00     
      4       -2.693842e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 184
      1       1.414149e+00     
      2       -1.439291e+00    
      3       1.687090e+00     
      4       -2.556974e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 185
      1       1.413640e+00     
      2       -1.438284e+00    
      3       1.680568e+00     
      4       -2.430264e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 186
      1       1.413141e+00     
      2       -1.437297e+00    
      3       1.674178e+00     
      4       -2.312750e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 187
      1       1.412652e+00     
      2       -1.436332e+00    
      3       1.667918e+00     
      4       -2.203583e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 188
      1       1.412173e+00     
      2       -1.435386e+00    
      3       1.661785e+00     
      4       -2.102003e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 189
      1       1.411703e+00     
      2       -1.434461e+00    
      3       1.655776e+00     
      4       -2.007335e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 190
      1       1.411243e+00     
      2       -1.433555e+00    
      3       1.649890e+00     
      4       -1.918975e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 191
      1       1.410792e+00     
      2       -1.432668e+00    
      3       1.644124e+00     
      4       -1.836382e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 192
      1       1.410350e+00     
      2       -1.431800e+00    
      3       1.638474e+00     
      4       -1.759073e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 193
      1       1.409918e+00     
      2       -1.430950e+00    
      3       1.632940e+00     
      4       -1.686610e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 194
      1       1.409494e+00     
      2       -1.430118e+00    
      3       1.627519e+00     
      4       -1.618602e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 195
      1       1.409080e+00     
      2       -1.429304e+00    
      3       1.622208e+00     
      4       -1.554695e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 196
      1       1.408674e+00     
      2       -1.428507e+00    
      3       1.617005e+00     
      4       -1.494569e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 197
      1       1.408276e+00     
      2       -1.427727e+00    
      3       1.611909e+00     
      4       -1.437934e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 198
      1       1.407888e+00     
      2       -1.426963e+00    
      3       1.606916e+00     
      4       -1.384528e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 199
      1       1.407507e+00     
      2       -1.426216e+00    
      3       1.602026e+00     
      4       -1.334111e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 200
      1       1.407135e+00     
      2       -1.425485e+00    
      3       1.597236e+00     
      4       -1.286468e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 201
      1       1.406771e+00     
      2       -1.424770e+00    
      3       1.592544e+00     
      4       -1.241400e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 202
      1       1.406415e+00     
      2       -1.424070e+00    
      3       1.587948e+00     
      4       -1.198726e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 203
      1       1.406066e+00     
      2       -1.423385e+00    
      3       1.583447e+00     
      4       -1.158282e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 204
      1       1.405725e+00     
      2       -1.422714e+00    
      3       1.579039e+00     
      4       -1.119915e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 205
      1       1.405392e+00     
      2       -1.422058e+00    
      3       1.574721e+00     
      4       -1.083488e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 206
      1       1.405066e+00     
      2       -1.421417e+00    
      3       1.570493e+00     
      4       -1.048873e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 207
      1       1.404748e+00     
      2       -1.420789e+00    
      3       1.566352e+00     
      4       -1.015953e+01    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 208
      1       1.404436e+00     
      2       -1.420174e+00    
      3       1.562297e+00     
      4       -9.846199e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 209
      1       1.404132e+00     
      2       -1.419573e+00    
      3       1.558326e+00     
      4       -9.547749e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 210
      1       1.403834e+00     
      2       -1.418985e+00    
      3       1.554437e+00     
      4       -9.263261e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 211
      1       1.403543e+00     
      2       -1.418410e+00    
      3       1.550630e+00     
      4       -8.991887e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 212
      1       1.403259e+00     
      2       -1.417847e+00    
      3       1.546902e+00     
      4       -8.732845e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 213
      1       1.402982e+00     
      2       -1.417296e+00    
      3       1.543252e+00     
      4       -8.485407e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 214
      1       1.402710e+00     
      2       -1.416757e+00    
      3       1.539679e+00     
      4       -8.248900e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 215
      1       1.402445e+00     
      2       -1.416230e+00    
      3       1.536181e+00     
      4       -8.022699e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 216
      1       1.402186e+00     
      2       -1.415714e+00    
      3       1.532757e+00     
      4       -7.806223e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 217
      1       1.401934e+00     
      2       -1.415210e+00    
      3       1.529405e+00     
      4       -7.598932e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 218
      1       1.401687e+00     
      2       -1.414716e+00    
      3       1.526125e+00     
      4       -7.400322e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 219
      1       1.401445e+00     
      2       -1.414234e+00    
      3       1.522914e+00     
      4       -7.209923e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 220
      1       1.401210e+00     
      2       -1.413762e+00    
      3       1.519771e+00     
      4       -7.027298e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 221
      1       1.400980e+00     
      2       -1.413300e+00    
      3       1.516696e+00     
      4       -6.852038e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 222
      1       1.400755e+00     
      2       -1.412848e+00    
      3       1.513686e+00     
      4       -6.683761e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 223
      1       1.400536e+00     
      2       -1.412406e+00    
      3       1.510742e+00     
      4       -6.522109e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 224
      1       1.400322e+00     
      2       -1.411974e+00    
      3       1.507860e+00     
      4       -6.366747e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 225
      1       1.400113e+00     
      2       -1.411551e+00    
      3       1.505041e+00     
      4       -6.217360e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 226
      1       1.399909e+00     
      2       -1.411138e+00    
      3       1.502284e+00     
      4       -6.073655e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 227
      1       1.399710e+00     
      2       -1.410734e+00    
      3       1.499586e+00     
      4       -5.935355e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 228
      1       1.399515e+00     
      2       -1.410338e+00    
      3       1.496947e+00     
      4       -5.802200e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 229
      1       1.399326e+00     
      2       -1.409951e+00    
      3       1.494366e+00     
      4       -5.673945e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 230
      1       1.399140e+00     
      2       -1.409573e+00    
      3       1.491842e+00     
      4       -5.550361e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 231
      1       1.398960e+00     
      2       -1.409203e+00    
      3       1.489373e+00     
      4       -5.431231e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 232
      1       1.398784e+00     
      2       -1.408841e+00    
      3       1.486959e+00     
      4       -5.316351e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 233
      1       1.398612e+00     
      2       -1.408487e+00    
      3       1.484599e+00     
      4       -5.205529e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 234
      1       1.398444e+00     
      2       -1.408141e+00    
      3       1.482291e+00     
      4       -5.098582e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 235
      1       1.398280e+00     
      2       -1.407802e+00    
      3       1.480035e+00     
      4       -4.995339e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 236
      1       1.398120e+00     
      2       -1.407471e+00    
      3       1.477830e+00     
      4       -4.895638e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 237
      1       1.397964e+00     
      2       -1.407147e+00    
      3       1.475674e+00     
      4       -4.799326e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 238
      1       1.397812e+00     
      2       -1.406831e+00    
      3       1.473567e+00     
      4       -4.706257e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 239
      1       1.397664e+00     
      2       -1.406521e+00    
      3       1.471507e+00     
      4       -4.616294e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 240
      1       1.397519e+00     
      2       -1.406218e+00    
      3       1.469495e+00     
      4       -4.529308e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 241
      1       1.397378e+00     
      2       -1.405922e+00    
      3       1.467528e+00     
      4       -4.445173e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 242
      1       1.397241e+00     
      2       -1.405632e+00    
      3       1.465607e+00     
      4       -4.363774e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 243
      1       1.397106e+00     
      2       -1.405349e+00    
      3       1.463730e+00     
      4       -4.285000e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 244
      1       1.396975e+00     
      2       -1.405072e+00    
      3       1.461896e+00     
      4       -4.208744e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 245
      1       1.396848e+00     
      2       -1.404801e+00    
      3       1.460104e+00     
      4       -4.134906e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 246
      1       1.396723e+00     
      2       -1.404537e+00    
      3       1.458355e+00     
      4       -4.063392e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 247
      1       1.396602e+00     
      2       -1.404278e+00    
      3       1.456646e+00     
      4       -3.994109e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 248
      1       1.396483e+00     
      2       -1.404024e+00    
      3       1.454977e+00     
      4       -3.926973e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 249
      1       1.396368e+00     
      2       -1.403777e+00    
      3       1.453347e+00     
      4       -3.861901e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 250
      1       1.396255e+00     
      2       -1.403534e+00    
      3       1.451756e+00     
      4       -3.798814e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 251
      1       1.396145e+00     
      2       -1.403298e+00    
      3       1.450203e+00     
      4       -3.737638e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 252
      1       1.396038e+00     
      2       -1.403066e+00    
      3       1.448686e+00     
      4       -3.678302e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 253
      1       1.395934e+00     
      2       -1.402840e+00    
      3       1.447206e+00     
      4       -3.620737e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 254
      1       1.395832e+00     
      2       -1.402618e+00    
      3       1.445761e+00     
      4       -3.564880e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 255
      1       1.395733e+00     
      2       -1.402402e+00    
      3       1.444351e+00     
      4       -3.510667e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 256
      1       1.395636e+00     
      2       -1.402190e+00    
      3       1.442975e+00     
      4       -3.458041e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 257
      1       1.395542e+00     
      2       -1.401983e+00    
      3       1.441632e+00     
      4       -3.406944e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 258
      1       1.395450e+00     
      2       -1.401780e+00    
      3       1.440322e+00     
      4       -3.357322e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 259
      1       1.395360e+00     
      2       -1.401582e+00    
      3       1.439043e+00     
      4       -3.309123e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 260
      1       1.395272e+00     
      2       -1.401389e+00    
      3       1.437796e+00     
      4       -3.262299e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 261
      1       1.395187e+00     
      2       -1.401199e+00    
      3       1.436580e+00     
      4       -3.216802e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 262
      1       1.395104e+00     
      2       -1.401014e+00    
      3       1.435393e+00     
      4       -3.172586e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 263
      1       1.395023e+00     
      2       -1.400833e+00    
      3       1.434236e+00     
      4       -3.129607e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 264
      1       1.394944e+00     
      2       -1.400656e+00    
      3       1.433107e+00     
      4       -3.087825e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 265
      1       1.394867e+00     
      2       -1.400483e+00    
      3       1.432007e+00     
      4       -3.047199e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 266
      1       1.394792e+00     
      2       -1.400314e+00    
      3       1.430934e+00     
      4       -3.007691e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 267
      1       1.394718e+00     
      2       -1.400149e+00    
      3       1.429888e+00     
      4       -2.969264e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 268
      1       1.394647e+00     
      2       -1.399987e+00    
      3       1.428868e+00     
      4       -2.931883e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 269
      1       1.394577e+00     
      2       -1.399829e+00    
      3       1.427874e+00     
      4       -2.895514e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 270
      1       1.394509e+00     
      2       -1.399674e+00    
      3       1.426905e+00     
      4       -2.860124e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 271
      1       1.394443e+00     
      2       -1.399523e+00    
      3       1.425960e+00     
      4       -2.825682e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 272
      1       1.394379e+00     
      2       -1.399375e+00    
      3       1.425040e+00     
      4       -2.792157e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 273
      1       1.394316e+00     
      2       -1.399230e+00    
      3       1.424143e+00     
      4       -2.759522e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 274
      1       1.394254e+00     
      2       -1.399089e+00    
      3       1.423269e+00     
      4       -2.727748e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 275
      1       1.394194e+00     
      2       -1.398950e+00    
      3       1.422418e+00     
      4       -2.696808e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 276
      1       1.394136e+00     
      2       -1.398815e+00    
      3       1.421588e+00     
      4       -2.666676e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 277
      1       1.394079e+00     
      2       -1.398683e+00    
      3       1.420780e+00     
      4       -2.637329e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 278
      1       1.394024e+00     
      2       -1.398553e+00    
      3       1.419993e+00     
      4       -2.608741e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 279
      1       1.393969e+00     
      2       -1.398427e+00    
      3       1.419226e+00     
      4       -2.580889e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 280
      1       1.393917e+00     
      2       -1.398303e+00    
      3       1.418479e+00     
      4       -2.553753e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 281
      1       1.393865e+00     
      2       -1.398182e+00    
      3       1.417752e+00     
      4       -2.527309e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 282
      1       1.393815e+00     
      2       -1.398064e+00    
      3       1.417044e+00     
      4       -2.501539e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 283
      1       1.393766e+00     
      2       -1.397949e+00    
      3       1.416355e+00     
      4       -2.476421e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 284
      1       1.393718e+00     
      2       -1.397835e+00    
      3       1.415683e+00     
      4       -2.451936e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 285
      1       1.393671e+00     
      2       -1.397725e+00    
      3       1.415030e+00     
      4       -2.428066e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 286
      1       1.393625e+00     
      2       -1.397617e+00    
      3       1.414394e+00     
      4       -2.404794e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 287
      1       1.393581e+00     
      2       -1.397511e+00    
      3       1.413774e+00     
      4       -2.382101e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 288
      1       1.393538e+00     
      2       -1.397408e+00    
      3       1.413171e+00     
      4       -2.359972e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 289
      1       1.393495e+00     
      2       -1.397307e+00    
      3       1.412585e+00     
      4       -2.338390e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 290
      1       1.393454e+00     
      2       -1.397208e+00    
      3       1.412014e+00     
      4       -2.317339e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 291
      1       1.393413e+00     
      2       -1.397111e+00    
      3       1.411458e+00     
      4       -2.296805e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 292
      1       1.393374e+00     
      2       -1.397016e+00    
      3       1.410918e+00     
      4       -2.276773e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 293
      1       1.393335e+00     
      2       -1.396924e+00    
      3       1.410392e+00     
      4       -2.257229e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 294
      1       1.393298e+00     
      2       -1.396834e+00    
      3       1.409880e+00     
      4       -2.238159e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 295
      1       1.393261e+00     
      2       -1.396745e+00    
      3       1.409382e+00     
      4       -2.219551e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 296
      1       1.393225e+00     
      2       -1.396659e+00    
      3       1.408898e+00     
      4       -2.201391e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 297
      1       1.393190e+00     
      2       -1.396574e+00    
      3       1.408427e+00     
      4       -2.183668e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 298
      1       1.393156e+00     
      2       -1.396491e+00    
      3       1.407969e+00     
      4       -2.166369e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 299
      1       1.393122e+00     
      2       -1.396410e+00    
      3       1.407523e+00     
      4       -2.149482e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 300
      1       1.393089e+00     
      2       -1.396331e+00    
      3       1.407090e+00     
      4       -2.132998e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 301
      1       1.393057e+00     
      2       -1.396254e+00    
      3       1.406669e+00     
      4       -2.116904e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 302
      1       1.393026e+00     
      2       -1.396178e+00    
      3       1.406259e+00     
      4       -2.101191e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 303
      1       1.392995e+00     
      2       -1.396104e+00    
      3       1.405861e+00     
      4       -2.085849e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 304
      1       1.392965e+00     
      2       -1.396032e+00    
      3       1.405473e+00     
      4       -2.070867e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 305
      1       1.392936e+00     
      2       -1.395961e+00    
      3       1.405097e+00     
      4       -2.056235e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 306
      1       1.392907e+00     
      2       -1.395892e+00    
      3       1.404731e+00     
      4       -2.041946e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 307
      1       1.392879e+00     
      2       -1.395824e+00    
      3       1.404375e+00     
      4       -2.027989e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 308
      1       1.392851e+00     
      2       -1.395758e+00    
      3       1.404030e+00     
      4       -2.014357e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 309
      1       1.392824e+00     
      2       -1.395693e+00    
      3       1.403694e+00     
      4       -2.001040e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 310
      1       1.392798e+00     
      2       -1.395629e+00    
      3       1.403367e+00     
      4       -1.988031e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 311
      1       1.392772e+00     
      2       -1.395567e+00    
      3       1.403050e+00     
      4       -1.975322e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 312
      1       1.392747e+00     
      2       -1.395507e+00    
      3       1.402742e+00     
      4       -1.962904e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 313
      1       1.392722e+00     
      2       -1.395447e+00    
      3       1.402442e+00     
      4       -1.950771e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 314
      1       1.392697e+00     
      2       -1.395389e+00    
      3       1.402151e+00     
      4       -1.938915e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 315
      1       1.392673e+00     
      2       -1.395333e+00    
      3       1.401869e+00     
      4       -1.927330e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 316
      1       1.392649e+00     
      2       -1.395277e+00    
      3       1.401594e+00     
      4       -1.916008e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 317
      1       1.392626e+00     
      2       -1.395223e+00    
      3       1.401328e+00     
      4       -1.904943e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 318
      1       1.392603e+00     
      2       -1.395170e+00    
      3       1.401069e+00     
      4       -1.894128e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 319
      1       1.392581e+00     
      2       -1.395118e+00    
      3       1.400818e+00     
      4       -1.883557e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 320
      1       1.392559e+00     
      2       -1.395067e+00    
      3       1.400574e+00     
      4       -1.873224e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 321
      1       1.392537e+00     
      2       -1.395017e+00    
      3       1.400337e+00     
      4       -1.863124e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 322
      1       1.392516e+00     
      2       -1.394968e+00    
      3       1.400106e+00     
      4       -1.853250e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 323
      1       1.392495e+00     
      2       -1.394921e+00    
      3       1.399883e+00     
      4       -1.843597e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 324
      1       1.392474e+00     
      2       -1.394874e+00    
      3       1.399666e+00     
      4       -1.834159e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 325
      1       1.392454e+00     
      2       -1.394828e+00    
      3       1.399456e+00     
      4       -1.824931e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 326
      1       1.392433e+00     
      2       -1.394784e+00    
      3       1.399252e+00     
      4       -1.815908e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 327
      1       1.392414e+00     
      2       -1.394740e+00    
      3       1.399054e+00     
      4       -1.807086e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 328
      1       1.392394e+00     
      2       -1.394697e+00    
      3       1.398862e+00     
      4       -1.798458e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 329
      1       1.392375e+00     
      2       -1.394655e+00    
      3       1.398675e+00     
      4       -1.790021e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 330
      1       1.392355e+00     
      2       -1.394614e+00    
      3       1.398494e+00     
      4       -1.781770e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 331
      1       1.392337e+00     
      2       -1.394574e+00    
      3       1.398319e+00     
      4       -1.773701e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 332
      1       1.392318e+00     
      2       -1.394535e+00    
      3       1.398149e+00     
      4       -1.765808e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 333
      1       1.392299e+00     
      2       -1.394497e+00    
      3       1.397984e+00     
      4       -1.758089e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 334
      1       1.392281e+00     
      2       -1.394459e+00    
      3       1.397824e+00     
      4       -1.750538e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 335
      1       1.392263e+00     
      2       -1.394423e+00    
      3       1.397669e+00     
      4       -1.743152e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 336
      1       1.392245e+00     
      2       -1.394387e+00    
      3       1.397518e+00     
      4       -1.735927e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 337
      1       1.392227e+00     
      2       -1.394351e+00    
      3       1.397373e+00     
      4       -1.728859e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 338
      1       1.392209e+00     
      2       -1.394317e+00    
      3       1.397232e+00     
      4       -1.721945e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 339
      1       1.392192e+00     
      2       -1.394283e+00    
      3       1.397095e+00     
      4       -1.715180e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 340
      1       1.392175e+00     
      2       -1.394250e+00    
      3       1.396962e+00     
      4       -1.708561e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 341
      1       1.392157e+00     
      2       -1.394218e+00    
      3       1.396834e+00     
      4       -1.702086e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 342
      1       1.392140e+00     
      2       -1.394186e+00    
      3       1.396710e+00     
      4       -1.695750e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 343
      1       1.392123e+00     
      2       -1.394155e+00    
      3       1.396589e+00     
      4       -1.689550e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 344
      1       1.392106e+00     
      2       -1.394125e+00    
      3       1.396473e+00     
      4       -1.683484e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 345
      1       1.392090e+00     
      2       -1.394095e+00    
      3       1.396360e+00     
      4       -1.677547e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 346
      1       1.392073e+00     
      2       -1.394066e+00    
      3       1.396250e+00     
      4       -1.671738e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 347
      1       1.392056e+00     
      2       -1.394038e+00    
      3       1.396145e+00     
      4       -1.666053e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 348
      1       1.392040e+00     
      2       -1.394010e+00    
      3       1.396042e+00     
      4       -1.660489e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 349
      1       1.392023e+00     
      2       -1.393982e+00    
      3       1.395943e+00     
      4       -1.655044e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 350
      1       1.392007e+00     
      2       -1.393956e+00    
      3       1.395847e+00     
      4       -1.649715e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 351
      1       1.391991e+00     
      2       -1.393929e+00    
      3       1.395755e+00     
      4       -1.644499e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 352
      1       1.391975e+00     
      2       -1.393904e+00    
      3       1.395665e+00     
      4       -1.639394e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 353
      1       1.391959e+00     
      2       -1.393879e+00    
      3       1.395579e+00     
      4       -1.634397e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 354
      1       1.391943e+00     
      2       -1.393854e+00    
      3       1.395495e+00     
      4       -1.629505e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 355
      1       1.391927e+00     
      2       -1.393830e+00    
      3       1.395414e+00     
      4       -1.624717e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 356
      1       1.391911e+00     
      2       -1.393806e+00    
      3       1.395336e+00     
      4       -1.620030e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 357
      1       1.391895e+00     
      2       -1.393783e+00    
      3       1.395260e+00     
      4       -1.615442e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 358
      1       1.391879e+00     
      2       -1.393760e+00    
      3       1.395187e+00     
      4       -1.610950e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 359
      1       1.391864e+00     
      2       -1.393738e+00    
      3       1.395116e+00     
      4       -1.606553e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 360
      1       1.391848e+00     
      2       -1.393716e+00    
      3       1.395048e+00     
      4       -1.602248e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 361
      1       1.391833e+00     
      2       -1.393695e+00    
      3       1.394982e+00     
      4       -1.598033e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 362
      1       1.391817e+00     
      2       -1.393674e+00    
      3       1.394919e+00     
      4       -1.593907e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 363
      1       1.391802e+00     
      2       -1.393654e+00    
      3       1.394857e+00     
      4       -1.589867e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 364
      1       1.391787e+00     
      2       -1.393634e+00    
      3       1.394798e+00     
      4       -1.585911e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 365
      1       1.391771e+00     
      2       -1.393614e+00    
      3       1.394741e+00     
      4       -1.582037e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 366
      1       1.391756e+00     
      2       -1.393595e+00    
      3       1.394686e+00     
      4       -1.578245e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 367
      1       1.391741e+00     
      2       -1.393576e+00    
      3       1.394632e+00     
      4       -1.574531e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 368
      1       1.391727e+00     
      2       -1.393557e+00    
      3       1.394581e+00     
      4       -1.570895e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 369
      1       1.391712e+00     
      2       -1.393539e+00    
      3       1.394531e+00     
      4       -1.567334e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 370
      1       1.391697e+00     
      2       -1.393521e+00    
      3       1.394484e+00     
      4       -1.563846e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 371
      1       1.391683e+00     
      2       -1.393504e+00    
      3       1.394437e+00     
      4       -1.560431e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 372
      1       1.391668e+00     
      2       -1.393486e+00    
      3       1.394393e+00     
      4       -1.557087e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 373
      1       1.391654e+00     
      2       -1.393470e+00    
      3       1.394350e+00     
      4       -1.553812e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 374
      1       1.391640e+00     
      2       -1.393453e+00    
      3       1.394308e+00     
      4       -1.550604e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 375
      1       1.391626e+00     
      2       -1.393437e+00    
      3       1.394269e+00     
      4       -1.547463e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 376
      1       1.391612e+00     
      2       -1.393421e+00    
      3       1.394230e+00     
      4       -1.544386e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 377
      1       1.391598e+00     
      2       -1.393405e+00    
      3       1.394193e+00     
      4       -1.541373e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 378
      1       1.391585e+00     
      2       -1.393390e+00    
      3       1.394157e+00     
      4       -1.538422e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 379
      1       1.391571e+00     
      2       -1.393375e+00    
      3       1.394122e+00     
      4       -1.535531e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 380
      1       1.391558e+00     
      2       -1.393360e+00    
      3       1.394089e+00     
      4       -1.532700e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 381
      1       1.391545e+00     
      2       -1.393346e+00    
      3       1.394057e+00     
      4       -1.529926e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 382
      1       1.391532e+00     
      2       -1.393332e+00    
      3       1.394026e+00     
      4       -1.527210e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 383
      1       1.391519e+00     
      2       -1.393318e+00    
      3       1.393996e+00     
      4       -1.524549e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 384
      1       1.391506e+00     
      2       -1.393304e+00    
      3       1.393967e+00     
      4       -1.521942e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 385
      1       1.391494e+00     
      2       -1.393291e+00    
      3       1.393940e+00     
      4       -1.519389e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 386
      1       1.391481e+00     
      2       -1.393278e+00    
      3       1.393913e+00     
      4       -1.516888e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 387
      1       1.391469e+00     
      2       -1.393265e+00    
      3       1.393887e+00     
      4       -1.514438e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 388
      1       1.391457e+00     
      2       -1.393252e+00    
      3       1.393862e+00     
      4       -1.512037e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 389
      1       1.391446e+00     
      2       -1.393240e+00    
      3       1.393838e+00     
      4       -1.509686e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 390
      1       1.391434e+00     
      2       -1.393227e+00    
      3       1.393815e+00     
      4       -1.507383e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 391
      1       1.391423e+00     
      2       -1.393215e+00    
      3       1.393792e+00     
      4       -1.505126e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 392
      1       1.391411e+00     
      2       -1.393203e+00    
      3       1.393771e+00     
      4       -1.502915e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 393
      1       1.391400e+00     
      2       -1.393192e+00    
      3       1.393750e+00     
      4       -1.500749e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 394
      1       1.391389e+00     
      2       -1.393180e+00    
      3       1.393730e+00     
      4       -1.498627e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 395
      1       1.391379e+00     
      2       -1.393169e+00    
      3       1.393711e+00     
      4       -1.496547e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 396
      1       1.391368e+00     
      2       -1.393158e+00    
      3       1.393692e+00     
      4       -1.494510e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 397
      1       1.391358e+00     
      2       -1.393147e+00    
      3       1.393674e+00     
      4       -1.492515e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 398
      1       1.391348e+00     
      2       -1.393136e+00    
      3       1.393657e+00     
      4       -1.490559e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 399
      1       1.391338e+00     
      2       -1.393126e+00    
      3       1.393640e+00     
      4       -1.488643e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 400
      1       1.391328e+00     
      2       -1.393116e+00    
      3       1.393624e+00     
      4       -1.486766e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 401
      1       1.391319e+00     
      2       -1.393105e+00    
      3       1.393608e+00     
      4       -1.484926e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 402
      1       1.391309e+00     
      2       -1.393095e+00    
      3       1.393593e+00     
      4       -1.483124e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 403
      1       1.391300e+00     
      2       -1.393086e+00    
      3       1.393578e+00     
      4       -1.481358e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 404
      1       1.391291e+00     
      2       -1.393076e+00    
      3       1.393564e+00     
      4       -1.479627e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 405
      1       1.391282e+00     
      2       -1.393066e+00    
      3       1.393550e+00     
      4       -1.477931e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 406
      1       1.391274e+00     
      2       -1.393057e+00    
      3       1.393537e+00     
      4       -1.476270e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 407
      1       1.391265e+00     
      2       -1.393048e+00    
      3       1.393525e+00     
      4       -1.474641e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 408
      1       1.391257e+00     
      2       -1.393039e+00    
      3       1.393512e+00     
      4       -1.473046e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 409
      1       1.391249e+00     
      2       -1.393030e+00    
      3       1.393501e+00     
      4       -1.471482e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 410
      1       1.391241e+00     
      2       -1.393021e+00    
      3       1.393489e+00     
      4       -1.469950e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 411
      1       1.391233e+00     
      2       -1.393012e+00    
      3       1.393478e+00     
      4       -1.468448e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 412
      1       1.391226e+00     
      2       -1.393004e+00    
      3       1.393467e+00     
      4       -1.466977e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 413
      1       1.391218e+00     
      2       -1.392995e+00    
      3       1.393457e+00     
      4       -1.465534e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 414
      1       1.391211e+00     
      2       -1.392987e+00    
      3       1.393447e+00     
      4       -1.464121e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 415
      1       1.391204e+00     
      2       -1.392979e+00    
      3       1.393437e+00     
      4       -1.462736e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 416
      1       1.391197e+00     
      2       -1.392971e+00    
      3       1.393428e+00     
      4       -1.461379e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 417
      1       1.391190e+00     
      2       -1.392963e+00    
      3       1.393419e+00     
      4       -1.460049e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 418
      1       1.391184e+00     
      2       -1.392955e+00    
      3       1.393410e+00     
      4       -1.458745e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 419
      1       1.391177e+00     
      2       -1.392947e+00    
      3       1.393402e+00     
      4       -1.457467e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 420
      1       1.391171e+00     
      2       -1.392939e+00    
      3       1.393394e+00     
      4       -1.456215e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 421
      1       1.391165e+00     
      2       -1.392932e+00    
      3       1.393386e+00     
      4       -1.454988e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 422
      1       1.391159e+00     
      2       -1.392924e+00    
      3       1.393378e+00     
      4       -1.453785e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 423
      1       1.391153e+00     
      2       -1.392917e+00    
      3       1.393371e+00     
      4       -1.452606e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 424
      1       1.391147e+00     
      2       -1.392910e+00    
      3       1.393364e+00     
      4       -1.451451e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 425
      1       1.391141e+00     
      2       -1.392902e+00    
      3       1.393357e+00     
      4       -1.450318e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 426
      1       1.391136e+00     
      2       -1.392895e+00    
      3       1.393350e+00     
      4       -1.449208e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 427
      1       1.391131e+00     
      2       -1.392888e+00    
      3       1.393344e+00     
      4       -1.448120e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 428
      1       1.391125e+00     
      2       -1.392881e+00    
      3       1.393337e+00     
      4       -1.447054e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 429
      1       1.391120e+00     
      2       -1.392875e+00    
      3       1.393331e+00     
      4       -1.446009e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 430
      1       1.391115e+00     
      2       -1.392868e+00    
      3       1.393325e+00     
      4       -1.444985e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 431
      1       1.391110e+00     
      2       -1.392861e+00    
      3       1.393320e+00     
      4       -1.443980e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 432
      1       1.391106e+00     
      2       -1.392854e+00    
      3       1.393314e+00     
      4       -1.442996e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 433
      1       1.391101e+00     
      2       -1.392848e+00    
      3       1.393309e+00     
      4       -1.442031e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 434
      1       1.391097e+00     
      2       -1.392841e+00    
      3       1.393304e+00     
      4       -1.441086e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 435
      1       1.391092e+00     
      2       -1.392835e+00    
      3       1.393299e+00     
      4       -1.440159e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 436
      1       1.391088e+00     
      2       -1.392829e+00    
      3       1.393294e+00     
      4       -1.439250e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 437
      1       1.391084e+00     
      2       -1.392822e+00    
      3       1.393289e+00     
      4       -1.438360e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 438
      1       1.391080e+00     
      2       -1.392816e+00    
      3       1.393285e+00     
      4       -1.437487e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 439
      1       1.391076e+00     
      2       -1.392810e+00    
      3       1.393280e+00     
      4       -1.436631e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 440
      1       1.391072e+00     
      2       -1.392804e+00    
      3       1.393276e+00     
      4       -1.435792e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 441
      1       1.391068e+00     
      2       -1.392798e+00    
      3       1.393272e+00     
      4       -1.434970e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 442
      1       1.391065e+00     
      2       -1.392792e+00    
      3       1.393268e+00     
      4       -1.434164e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 443
      1       1.391061e+00     
      2       -1.392786e+00    
      3       1.393264e+00     
      4       -1.433374e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 444
      1       1.391058e+00     
      2       -1.392780e+00    
      3       1.393260e+00     
      4       -1.432599e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 445
      1       1.391054e+00     
      2       -1.392774e+00    
      3       1.393257e+00     
      4       -1.431840e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 446
      1       1.391051e+00     
      2       -1.392769e+00    
      3       1.393253e+00     
      4       -1.431096e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 447
      1       1.391048e+00     
      2       -1.392763e+00    
      3       1.393250e+00     
      4       -1.430366e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 448
      1       1.391045e+00     
      2       -1.392757e+00    
      3       1.393246e+00     
      4       -1.429651e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 449
      1       1.391042e+00     
      2       -1.392752e+00    
      3       1.393243e+00     
      4       -1.428950e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 450
      1       1.391039e+00     
      2       -1.392746e+00    
      3       1.393240e+00     
      4       -1.428263e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 451
      1       1.391036e+00     
      2       -1.392740e+00    
      3       1.393237e+00     
      4       -1.427589e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 452
      1       1.391033e+00     
      2       -1.392735e+00    
      3       1.393234e+00     
      4       -1.426928e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 453
      1       1.391030e+00     
      2       -1.392729e+00    
      3       1.393231e+00     
      4       -1.426281e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 454
      1       1.391028e+00     
      2       -1.392724e+00    
      3       1.393228e+00     
      4       -1.425646e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 455
      1       1.391025e+00     
      2       -1.392719e+00    
      3       1.393226e+00     
      4       -1.425023e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 456
      1       1.391023e+00     
      2       -1.392713e+00    
      3       1.393223e+00     
      4       -1.424413e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 457
      1       1.391020e+00     
      2       -1.392708e+00    
      3       1.393221e+00     
      4       -1.423815e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 458
      1       1.391018e+00     
      2       -1.392702e+00    
      3       1.393218e+00     
      4       -1.423229e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 459
      1       1.391015e+00     
      2       -1.392697e+00    
      3       1.393216e+00     
      4       -1.422654e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 460
      1       1.391013e+00     
      2       -1.392692e+00    
      3       1.393214e+00     
      4       -1.422091e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 461
      1       1.391011e+00     
      2       -1.392687e+00    
      3       1.393211e+00     
      4       -1.421538e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 462
      1       1.391009e+00     
      2       -1.392682e+00    
      3       1.393209e+00     
      4       -1.420996e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 463
      1       1.391007e+00     
      2       -1.392676e+00    
      3       1.393207e+00     
      4       -1.420465e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 464
      1       1.391005e+00     
      2       -1.392671e+00    
      3       1.393205e+00     
      4       -1.419945e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 465
      1       1.391003e+00     
      2       -1.392666e+00    
      3       1.393203e+00     
      4       -1.419435e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 466
      1       1.391001e+00     
      2       -1.392661e+00    
      3       1.393201e+00     
      4       -1.418934e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 467
      1       1.390999e+00     
      2       -1.392656e+00    
      3       1.393199e+00     
      4       -1.418444e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 468
      1       1.390997e+00     
      2       -1.392651e+00    
      3       1.393198e+00     
      4       -1.417963e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 469
      1       1.390995e+00     
      2       -1.392646e+00    
      3       1.393196e+00     
      4       -1.417491e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 470
      1       1.390993e+00     
      2       -1.392641e+00    
      3       1.393194e+00     
      4       -1.417029e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 471
      1       1.390992e+00     
      2       -1.392636e+00    
      3       1.393192e+00     
      4       -1.416576e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 472
      1       1.390990e+00     
      2       -1.392631e+00    
      3       1.393191e+00     
      4       -1.416132e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 473
      1       1.390988e+00     
      2       -1.392626e+00    
      3       1.393189e+00     
      4       -1.415696e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 474
      1       1.390987e+00     
      2       -1.392621e+00    
      3       1.393188e+00     
      4       -1.415269e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 475
      1       1.390985e+00     
      2       -1.392616e+00    
      3       1.393186e+00     
      4       -1.414851e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 476
      1       1.390984e+00     
      2       -1.392611e+00    
      3       1.393185e+00     
      4       -1.414440e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 477
      1       1.390982e+00     
      2       -1.392606e+00    
      3       1.393184e+00     
      4       -1.414038e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 478
      1       1.390981e+00     
      2       -1.392601e+00    
      3       1.393182e+00     
      4       -1.413643e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 0
 
     ITERATION 479
      1       1.390980e+00     
      2       -1.392596e+00    
      3       1.393181e+00     
      4       -1.413257e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 1
 
     ITERATION 480
      1       1.390978e+00     
      2       -1.392591e+00    
      3       1.393180e+00     
      4       -1.412877e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 1
 
     ITERATION 481
      1       1.390977e+00     
      2       -1.392586e+00    
      3       1.393178e+00     
      4       -1.412506e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 1
 
     ITERATION 482
      1       1.390976e+00     
      2       -1.392581e+00    
      3       1.393177e+00     
      4       -1.412141e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 1
 
     ITERATION 483
      1       1.390975e+00     
      2       -1.392576e+00    
      3       1.393176e+00     
      4       -1.411784e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 1
 
     ITERATION 484
      1       1.390973e+00     
      2       -1.392571e+00    
      3       1.393175e+00     
      4       -1.411434e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 1
 
     ITERATION 485
      1       1.390972e+00     
      2       -1.392566e+00    
      3       1.393174e+00     
      4       -1.411090e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 1
 
     ITERATION 486
      1       1.390971e+00     
      2       -1.392561e+00    
      3       1.393173e+00     
      4       -1.410754e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 1
 
     ITERATION 487
      1       1.390970e+00     
      2       -1.392556e+00    
      3       1.393172e+00     
      4       -1.410424e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 1
 
     ITERATION 488
      1       1.390969e+00     
      2       -1.392552e+00    
      3       1.393171e+00     
      4       -1.410100e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 1
 
     ITERATION 489
      1       1.390968e+00     
      2       -1.392547e+00    
      3       1.393170e+00     
      4       -1.409783e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 1
 
     ITERATION 490
      1       1.390967e+00     
      2       -1.392542e+00    
      3       1.393169e+00     
      4       -1.409472e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 1
 
     ITERATION 491
      1       1.390966e+00     
      2       -1.392537e+00    
      3       1.393168e+00     
      4       -1.409167e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 1
 
     ITERATION 492
      1       1.390965e+00     
      2       -1.392532e+00    
      3       1.393167e+00     
      4       -1.408868e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 1
 
     ITERATION 493
      1       1.390964e+00     
      2       -1.392527e+00    
      3       1.393166e+00     
      4       -1.408575e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 1
 
     ITERATION 494
      1       1.390963e+00     
      2       -1.392522e+00    
      3       1.393165e+00     
      4       -1.408287e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 1
 
     ITERATION 495
      1       1.390962e+00     
      2       -1.392517e+00    
      3       1.393165e+00     
      4       -1.408006e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 1
 
     ITERATION 496
      1       1.390961e+00     
      2       -1.392512e+00    
      3       1.393164e+00     
      4       -1.407729e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 1
 
     ITERATION 497
      1       1.390960e+00     
      2       -1.392507e+00    
      3       1.393163e+00     
      4       -1.407459e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 1
 
     ITERATION 498
      1       1.390960e+00     
      2       -1.392502e+00    
      3       1.393162e+00     
      4       -1.407193e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 1
 
     ITERATION 499
      1       1.390959e+00     
      2       -1.392497e+00    
      3       1.393162e+00     
      4       -1.406933e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 1
 
     ITERATION 500
      1       1.390958e+00     
      2       -1.392492e+00    
      3       1.393161e+00     
      4       -1.406678e+00    
 
     NUMBER OF EIGENVALUES CONVERGED UPTO THIS ITERATION = 1

 ***ERROR: INCREASE THE NUMBER OF ITERATIONS TO GET THE REQUESTED NUMBER OF 
           EIGENVALUES



     ANALYSIS SUMMARY:
     TOTAL OF          1  INCREMENTS
                       0  CUTBACKS IN AUTOMATIC INCREMENTATION
                       1  ITERATIONS INCLUDING CONTACT ITERATIONS IF PRESENT
                       1  PASSES THROUGH THE EQUATION SOLVER OF WHICH 
                       1  INVOLVE MATRIX DECOMPOSITION, INCLUDING
                       0  DECOMPOSITION(S) OF THE MASS MATRIX
                       1  REORDERING OF EQUATIONS TO MINIMIZE WAVEFRONT
                       0  ADDITIONAL RESIDUAL EVALUATIONS FOR LINE SEARCHES
                       0  ADDITIONAL OPERATOR EVALUATIONS FOR LINE SEARCHES
                       1  WARNING MESSAGES DURING USER INPUT PROCESSING
                       0  WARNING MESSAGES DURING ANALYSIS
                       0  ANALYSIS WARNINGS ARE NUMERICAL PROBLEM MESSAGES
                       0  ANALYSIS WARNINGS ARE NEGATIVE EIGENVALUE MESSAGES
                       1  ERROR MESSAGES



     JOB TIME SUMMARY
       USER TIME (SEC)      =   60.300    
       SYSTEM TIME (SEC)    =   5.7000    
       TOTAL CPU TIME (SEC) =   66.000    
       WALLCLOCK TIME (SEC) =         67
